modernized

diff --git a/zshrc.d/100-common-golang b/zshrc.d/100-common-golang
--- a/zshrc.d/100-common-golang
+++ b/zshrc.d/100-common-golang
@@ -1,7 +1,14 @@
 export GOPATH=$HOME/workspace
 export GOROOT=$HOME/.go
-addpath $GOPATH/bin $GOROOT/bin
+
+# Add Go paths if GOROOT exists
+[ -d "$GOROOT" ] && addpath $GOROOT/bin
+[ -d "$GOPATH/bin" ] && addpath $GOPATH/bin
 
 function gotidy() {
-  find ./ -name go.mod -exec realpath {} ';' | awk '{print "dirname "$0}' | zsh | awk '{print "cd "$0" && go mod tidy -e"}' | zsh -x;
+  command -v go &>/dev/null || {
+    err "go command not found"
+    return 1
+  }
+  find ./ -name go.mod -exec realpath {} ';' | awk '{print "dirname "$0}' | zsh | awk '{print "cd "$0" && go mod tidy -e"}' | zsh -x
 }
